services:
  database:
    image: postgres:17.4-alpine3.21
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  migrations:
    build: .
    command: sh -c "npm ci --save-dev && npm run migrate"
    depends_on:
      - database
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  web_green: # New application version
    image: web:1.1.0
    depends_on:
      - database
      - migrations
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  web_blue: # Current application version
    image: web:1.0.0
    depends_on:
      - database
      - migrations
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  nginx:
    image: nginx:1.27.4-perl
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - web_green
      - web_blue
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
